### ISSUE TITLE
No instructions on building tolua when building conky with lua bindings

### ISSUE THREAD

**Issue by arclance** [antonio-malcolm/conky-configs#1]
Your guide on building conky does not have instructions on how to correctly build tolua against lua5.1 even though it stresses that this is necessary for compilation to work.

**Comment by antonio-malcolm** [comment]
I think, maybe, you've confused tolua with toluapp (A.K.A., tolua++)?
It's mentioned, concisely, that tolua _isn't_ compiled against the lua5.1-devel package (just above the little dependency diagram):

_"tolua (requires lua-devel)"_

tolua is compiled against lua-devel, and doesn't required any modification.
